### PR TITLE
fix: undefined agent runner

### LINKED ISSUE #56: If agent runner is not found, the error is never propagated to the caller
Agent runner runs in a background task and does not emit error and complete events.

### PR DESCRIPTION
**Pull request by ErezSha**
- when trying to create an agent, check if the agent type exists
- server now checks requested agent runner type exists before trying to run against it.
- ui brings up a toast to indicate "agent doesn't exist" error

closes #56

### CODE REVIEW

File: chat/src/components/chat/multimodal-input.tsx [hunk 1]
```diff
@@ -92,19 +92,37 @@ function PureMultimodalInput({
...
+              }
+              return acc;
+            }, ""),
+            agent_id: agentId,
+          },
+        });
+        queyrClient.invalidateQueries({
+          queryKey: ["get", "/api/sessions", {}],
+        });
+      } catch (error: any) {
```
Comment (asaf) [inline chat/src/components/chat/multimodal-input.tsx]: @ErezSha this code is not needed, better to parse the Error as JSON in https://github.com/flux0-ai/flux0/blob/develop/chat/src/lib/api/api.ts#L10

File: chat/src/components/chat/multimodal-input.tsx [hunk 2]
```diff
@@ -30,7 +30,7 @@ function PureMultimodalInput({
   handleSubmit: (
     event?: {
       preventDefault?: () => void;
-    },
+    }
```
Comment (asaf) [inline chat/src/components/chat/multimodal-input.tsx]: Please check why prettify removes post lines ","

**Review by asaf — COMMENTED** [review]
I already fixed these, just FYI
